-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 10:19:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Source` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Source` (
  `idSource` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `lien_source` VARCHAR(45) NULL,
  `commentaire` VARCHAR(45) NULL,
  PRIMARY KEY (`idSource`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persones` (
  `idpersones` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `date_naisance` VARCHAR(45) NULL,
  `date_deces` DATE NOT NULL,
  `lieu_naissance` VARCHAR(45) NULL,
  `lieu_dece` VARCHAR(45) NULL,
  `Source_idSource` INT NOT NULL,
  PRIMARY KEY (`idpersones`, `Source_idSource`),
  UNIQUE INDEX `idpersones_UNIQUE` (`idpersones` ASC) VISIBLE,
  INDEX `fk_persones_Source1_idx` (`Source_idSource` ASC) VISIBLE,
  CONSTRAINT `fk_persones_Source1`
    FOREIGN KEY (`Source_idSource`)
    REFERENCES `mydb`.`Source` (`idSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evenments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evenments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evenments` (
  `idevenments` INT NOT NULL,
  `date_evenment` VARCHAR(45) NOT NULL,
  `type_evenment` VARCHAR(45) NOT NULL,
  `lieu_evenement` VARCHAR(45) NULL,
  PRIMARY KEY (`idevenments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relation` (
  `persones_idpersones` INT NOT NULL,
  `persones_idpersones1` INT NOT NULL,
  `idrelation` VARCHAR(45) NULL,
  PRIMARY KEY (`persones_idpersones`, `persones_idpersones1`),
  INDEX `fk_persones_has_persones_persones1_idx` (`persones_idpersones1` ASC) VISIBLE,
  INDEX `fk_persones_has_persones_persones_idx` (`persones_idpersones` ASC) VISIBLE,
  CONSTRAINT `fk_persones_has_persones_persones`
    FOREIGN KEY (`persones_idpersones`)
    REFERENCES `mydb`.`persones` (`idpersones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persones_has_persones_persones1`
    FOREIGN KEY (`persones_idpersones1`)
    REFERENCES `mydb`.`persones` (`idpersones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persones_has_evenments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persones_has_evenments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persones_has_evenments` (
  `persones_idpersones` INT NOT NULL,
  `evenments_idevenments` INT NOT NULL,
  PRIMARY KEY (`persones_idpersones`, `evenments_idevenments`),
  INDEX `fk_persones_has_evenments_evenments1_idx` (`evenments_idevenments` ASC) VISIBLE,
  INDEX `fk_persones_has_evenments_persones1_idx` (`persones_idpersones` ASC) VISIBLE,
  CONSTRAINT `fk_persones_has_evenments_persones1`
    FOREIGN KEY (`persones_idpersones`)
    REFERENCES `mydb`.`persones` (`idpersones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persones_has_evenments_evenments1`
    FOREIGN KEY (`evenments_idevenments`)
    REFERENCES `mydb`.`evenments` (`idevenments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
