-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 22:26:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`union`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`union` ;

CREATE TABLE IF NOT EXISTS `mydb`.`union` (
  `idunion` INT NOT NULL,
  `type_union` VARCHAR(45) NOT NULL,
  `date_debut` DATE NULL,
  `lieu_evenement` VARCHAR(45) NULL,
  `date_fin` DATE NULL,
  PRIMARY KEY (`idunion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relation` (
  `id_relation` INT NOT NULL,
  `type_relation` VARCHAR(45) NULL,
  `id_parent` VARCHAR(45) NULL,
  `id_epouse` VARCHAR(45) NULL,
  `id_epous` VARCHAR(45) NULL,
  `persones_idpersones` INT NOT NULL,
  `persones_Source_idSource` INT NOT NULL,
  `union_idunion` INT NOT NULL,
  PRIMARY KEY (`id_relation`),
  INDEX `fk_relation_union1_idx` (`union_idunion` ASC) VISIBLE,
  CONSTRAINT `fk_relation_union1`
    FOREIGN KEY (`union_idunion`)
    REFERENCES `mydb`.`union` (`idunion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personnes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personnes` (
  `noGeneologique` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `nom_jeune_fille` VARCHAR(45) NULL,
  `observation` VARCHAR(45) NULL,
  `date_naisance` VARCHAR(45) NOT NULL,
  `lieu_naissance` VARCHAR(45) NULL,
  `date_mariage` VARCHAR(45) NULL,
  `lieu_mariage` VARCHAR(45) NULL,
  `lieu_dece` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  `lien_image` VARCHAR(45) NULL,
  `relation_id_relation` INT NOT NULL,
  PRIMARY KEY (`noGeneologique`),
  INDEX `fk_personnes_relation1_idx` (`relation_id_relation` ASC) VISIBLE,
  CONSTRAINT `fk_personnes_relation1`
    FOREIGN KEY (`relation_id_relation`)
    REFERENCES `mydb`.`relation` (`id_relation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
