-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 16:38:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persones` (
  `idpersones` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `date_naisance` VARCHAR(45) NULL,
  `date_deces` DATE NOT NULL,
  `lieu_naissance` VARCHAR(45) NULL,
  `lieu_dece` VARCHAR(45) NULL,
  `numero_geneologic` VARCHAR(45) NULL,
  `lien_image` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersones`),
  UNIQUE INDEX `idpersones_UNIQUE` (`idpersones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`union`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`union` ;

CREATE TABLE IF NOT EXISTS `mydb`.`union` (
  `idunion` INT NOT NULL,
  `type_union` VARCHAR(45) NOT NULL,
  `date_debut` DATE NULL,
  `lieu_evenement` VARCHAR(45) NULL,
  `date_fin` DATE NULL,
  PRIMARY KEY (`idunion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relation` (
  `id_relation` INT NOT NULL,
  `type_relation` VARCHAR(45) NULL,
  `id_parent` VARCHAR(45) NULL,
  `id_epouse` VARCHAR(45) NULL,
  `id_epous` VARCHAR(45) NULL,
  `persones_idpersones` INT NOT NULL,
  `persones_Source_idSource` INT NOT NULL,
  `union_idunion` INT NOT NULL,
  PRIMARY KEY (`id_relation`),
  INDEX `fk_relation_persones_idx` (`persones_idpersones` ASC, `persones_Source_idSource` ASC) VISIBLE,
  INDEX `fk_relation_union1_idx` (`union_idunion` ASC) VISIBLE,
  CONSTRAINT `fk_relation_persones`
    FOREIGN KEY (`persones_idpersones`)
    REFERENCES `mydb`.`persones` (`idpersones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_union1`
    FOREIGN KEY (`union_idunion`)
    REFERENCES `mydb`.`union` (`idunion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
